version: "3.7"
services:

  ############################
  ## Heimdall               ##
  ## https://heimdall.site/ ##
  ############################
  heimdall:
    container_name: heimdall
    hostname: heimdall
    image: linuxserver/heimdall:latest # https://hub.docker.com/r/linuxserver/heimdall
    restart: always
    # ports: # Uncomment ports lines if not use a reverse proxy
    #   - 80:80
    #   - 443:443
    # volumes: # Uncomment volumes lines for data persistance
    #   - /docker/heimdall/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TZ:-'Europe/Madrid'}
    networks:
      - DockerLAN


###########
## REDES ##
###########
networks:
  DockerLAN:  ## Red bridge propia ##
    name: DockerLAN
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
