version: "3.7"
services:

  ##########################################
  ## DynDNS (ddclient)                    ##
  ## https://github.com/ddclient/ddclient ##
  ##########################################
  # Add compose.dyndns.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.dyndns.yml

  ############################
  ## Heimdall               ##
  ## https://heimdall.site/ ##
  ############################
  # Add compose.heimdall.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.heimdall.yml

  ##########################
  ## MariaDB              ##
  ## https://mariadb.org/ ##
  ##########################
  # Add compose.mariadb.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.mariadb.yml

  ####################################
  ## Nginx Proxy Manager            ##
  ## https://nginxproxymanager.com/ ##
  ####################################
  # Add compose.npmanager.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.npmanager.yml

  #####################
  ## N8N             ##
  ## https://n8n.io/ ##
  #####################
  # Add compose.n8n.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.n8n.yml

  ##########################
  ## Node-RED             ##
  ## https://nodered.org/ ##
  ##########################
  # Add compose.nodered.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.nodered.yml

  ###############################
  ## Portainer                 ##
  ## https://www.portainer.io/ ##
  ###############################
  # Add compose.portainer.yml to COMPOSE_FILE variable on .env file:
  # COMPOSE_FILE=docker-compose.yml,(...),compose.portainer.yml


  #####################################################
  ## Plex & Plexdrive (Rapejim)                      ##
  ## https://www.plex.tv/                            ##
  ## https://github.com/rapejim/pms-plexdrive-docker ##
  #####################################################
  plex-cloud:
    container_name: PlexCloud
    hostname: PlexCloud
    image: rapejim/pms-plexdrive-docker:beta # https://hub.docker.com/r/rapejim/pms-plexdrive-docker
    restart: unless-stopped
    privileged: true
    ports: 
      - 32400:32400
    volumes:
      - /docker/PlexCloud/config:/config
      - /docker/PlexCloud/transcode:/transcode
    environment:
      TZ: Europe/Madrid
      PLEX_UID : ${UID:-1000}
      PLEX_GID : ${GID:-1000}
      PLEXDRIVE_MOUNT_POINT: /home/Plex/media
      CHANGE_CONFIG_DIR_OWNERSHIP: 'false'
      CHANGE_PLEXDRIVE_CONFIG_DIR_OWNERSHIP: 'true'
      # PLEX_CLAIM: XXXXXXXXXXXXXXXXXXXXXXXXXX
      EXTRA_PARAMS: --drive-id=0ACd3-O2oLDQUUk9PVA
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    network_mode: "bridge"

  ##################################################
  ## RcloneBrowser (kapitainsky)                  ##
  ## https://kapitainsky.github.io/RcloneBrowser/ ##
  ##################################################
  rclone-browser:
    container_name: RcloneBrowser
    hostname: RcloneBrowser
    image: romancin/rclonebrowser:latest # https://hub.docker.com/r/romancin/rclonebrowser
    restart: unless-stopped
    ports: 
      - 5800:5800
    volumes:
      - /docker/RcloneBrowser/config:/config
      - /docker/RcloneBrowser/shared:/shared
      - /docker/RcloneBrowser/media:/media
      #   ## SSL de webmin ##
      # - /etc/webmin/letsencrypt-cert.pem:/config/certs/web-fullchain.pem
      # - /etc/webmin/letsencrypt-key.pem:/config/certs/web-privkey.pem
    environment:
      USER_ID: ${UID:-1000}
      GROUP_ID: ${GID:-1000}
      TZ: Europe/Madrid
      SECURE_CONNECTION: 1
      DISPLAY_WIDTH: 1280
      DISPLAY_HEIGHT: 720
    networks:
      - DockerLAN


###########
## REDES ##
###########
networks:
  DockerLAN:  ## Red bridge propia ##
    name: DockerLAN
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
